const guestInput = document.getElementById('guestCount');
const hoursInput = document.getElementById('serviceHours');
const tierInput = document.getElementById('drinkTier');
const mobileBarInput = document.getElementById('mobileBar');
const travelFeeInput = document.getElementById('travelFee');
const guestValue = document.getElementById('guestValue');
const hoursValue = document.getElementById('hoursValue');
const pricingOutput = document.getElementById('pricingOutput');
const packagePricing = { basic:{base:450,includedBartenders:1}, signature:{base:750,includedBartenders:2}, premium:{base:1200,includedBartenders:2} };
function renderPricing(){const guests=+guestInput.value,hours=+hoursInput.value,tier=tierInput.value;guestValue.textContent=guests;hoursValue.textContent=hours;const selectedPackage=packagePricing[tier];const bartenders=Math.max(1,Math.ceil(guests/60));const extraBartenders=Math.max(0,bartenders-selectedPackage.includedBartenders);const extraBartenderCost=extraBartenders*250;const additionalHours=Math.max(0,hours-4);const extraHourCost=additionalHours*bartenders*100;const mobileBarCost=+mobileBarInput.value;const travelFee=travelFeeInput.checked?75:0;const subtotal=selectedPackage.base+extraBartenderCost+extraHourCost+mobileBarCost+travelFee;const min=Math.round(subtotal*.95),max=Math.round(subtotal*1.08);const liquorBottles=Math.ceil((guests*hours*.3)/14);pricingOutput.innerHTML=`<p><strong>Estimated Service:</strong> $${min.toLocaleString()} – $${max.toLocaleString()}</p><p><strong>Base Package:</strong> $${selectedPackage.base.toLocaleString()}</p><p><strong>Staff Recommended:</strong> ${bartenders} bartender(s)</p><p><strong>Estimated Add-ons:</strong> $${(extraBartenderCost+extraHourCost+mobileBarCost+travelFee).toLocaleString()}</p><p><strong>Estimated Liquor Bottles:</strong> ${liquorBottles}</p><p><small>Estimator reflects current planning assumptions and staffing ranges. Final quotes depend on event complexity, service style, and location.</small></p>`;}
['input','change'].forEach(evt=>{guestInput.addEventListener(evt,renderPricing);hoursInput.addEventListener(evt,renderPricing);tierInput.addEventListener(evt,renderPricing);mobileBarInput.addEventListener(evt,renderPricing);travelFeeInput.addEventListener(evt,renderPricing);});renderPricing();
const alcoholForm=document.getElementById('alcohol-form'),alcOutput=document.getElementById('alcoholOutput');
alcoholForm.addEventListener('submit',e=>{e.preventDefault();const guests=+document.getElementById('alcGuests').value,hours=+document.getElementById('alcHours').value,style=document.getElementById('alcStyle').value,totalDrinks=Math.round(guests*hours*.95);let beerPct=.4,winePct=.3,cocktailPct=.3;if(style==='beerWine'){beerPct=.55;winePct=.45;cocktailPct=0;}if(style==='cocktail'){beerPct=.2;winePct=.2;cocktailPct=.6;}const beerCases=Math.ceil(totalDrinks*beerPct/24),wineBottles=Math.ceil(totalDrinks*winePct/5),liquorBottles=Math.ceil(totalDrinks*cocktailPct/14);alcOutput.innerHTML=`<p><strong>Estimated drinks:</strong> ${totalDrinks}</p><p><strong>Beer cases:</strong> ${beerCases}</p><p><strong>Wine bottles:</strong> ${wineBottles}</p><p><strong>Liquor bottles:</strong> ${liquorBottles}</p><p><small>Clients provide alcohol. Pour Social coordinates staffing plus mixers, soda, juices, fruit, syrups, and garnishes.</small></p>`;});
const chatForm=document.getElementById('chatForm'),chatInput=document.getElementById('chatInput'),chatLog=document.getElementById('chatLog');
function assistantReply(message){const q=message.toLowerCase();if(q.includes('staff')||q.includes('bartender')) return 'Pour Social can staff events with bartenders based on guest count, package level, and service needs. We coordinate scheduling and quality control for the event.'; if(q.includes('100')&&q.includes('alcohol')) return 'For around 100 guests over 4 hours, quantities depend on menu style. A balanced event often starts with beer, wine, and roughly 14–18 liquor bottles.'; if(q.includes('mixers')||q.includes('provide')) return 'Yes — Pour Social provides mixers, soda, juices, fruit, syrups, garnishes, and bar tools. Clients provide alcohol.'; if(q.includes('package')||q.includes('pricing')) return 'Current starting rates are Basic $450, Signature $750, and Premium/Wedding $1,200+. Final pricing depends on staffing, hours, setup, and location.'; if(q.includes('menu')||q.includes('drink')) return 'We build menus around your event vibe. Most events run best with a focused list of signature drinks plus crowd favorites.'; return 'Great question. Submit the booking form with your date, guest count, and location and we will send a tailored recommendation.';}
chatForm.addEventListener('submit',e=>{e.preventDefault();const userText=chatInput.value.trim();if(!userText)return;chatLog.insertAdjacentHTML('beforeend',`<p><strong>You:</strong> ${userText}</p>`);chatLog.insertAdjacentHTML('beforeend',`<p><strong>Assistant:</strong> ${assistantReply(userText)}</p>`);chatInput.value='';chatLog.scrollTop=chatLog.scrollHeight;});
document.getElementById('year').textContent=new Date().getFullYear();const assistantDock=document.getElementById('assistantDock'),assistantToggle=document.getElementById('assistantToggle');assistantToggle.addEventListener('click',()=>{assistantDock.classList.toggle('is-collapsed');const expanded=!assistantDock.classList.contains('is-collapsed');assistantToggle.setAttribute('aria-expanded',String(expanded));assistantToggle.textContent=expanded?'Ask Pour Social':'Open Planning Assistant';});